/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dal.BancaDAL;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Banca;

/**
 *
 * @author rpmen
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jPanelOpcoes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelOpcoes = new javax.swing.JPanel();
        jLabelSair = new javax.swing.JLabel();
        jLabelMinhaConta = new javax.swing.JLabel();
        jLabelUsuarios = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelConfiguracoes = new javax.swing.JLabel();
        jPanelCabecalho = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelOpcoes = new javax.swing.JLabel();
        jPanelMenuLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelRelatorios = new javax.swing.JLabel();
        jLabelDashboard = new javax.swing.JLabel();
        jLabelProjetos = new javax.swing.JLabel();
        jLabelHistorico = new javax.swing.JLabel();
        jLabelBancas = new javax.swing.JLabel();
        jLabelEquipes = new javax.swing.JLabel();
        jPanelConteudoCentral = new javax.swing.JPanel();
        jPanelDashboard = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanelProjetos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabelNovoProjeto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjetos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTipoProjeto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxNegocio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxTipoProjetoEmpresa = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxMacrotema = new javax.swing.JComboBox<>();
        jComboBoxRisco = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxRisco1 = new javax.swing.JComboBox<>();
        jPanelEquipes = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEquipes = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabelNovaBanca1 = new javax.swing.JLabel();
        jPanelBancas = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jLabelNovaBanca = new javax.swing.JLabel();
        jLabelPesquisarBanca = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBancas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanelHistorico = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanelRelatorios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSair.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSair.setForeground(new java.awt.Color(0, 51, 102));
        jLabelSair.setText("   Sair");
        jLabelSair.setOpaque(true);
        jLabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSairMouseExited(evt);
            }
        });
        jPanelOpcoes.add(jLabelSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 50));

        jLabelMinhaConta.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMinhaConta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMinhaConta.setForeground(new java.awt.Color(0, 51, 102));
        jLabelMinhaConta.setText("   Minha Conta");
        jLabelMinhaConta.setOpaque(true);
        jLabelMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinhaContaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinhaContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinhaContaMouseExited(evt);
            }
        });
        jPanelOpcoes.add(jLabelMinhaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jLabelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsuarios.setForeground(new java.awt.Color(0, 51, 102));
        jLabelUsuarios.setText("   Usuários");
        jLabelUsuarios.setOpaque(true);
        jLabelUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelUsuariosMouseExited(evt);
            }
        });
        jPanelOpcoes.add(jLabelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 50));
        jPanelOpcoes.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 10));

        jLabelConfiguracoes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelConfiguracoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelConfiguracoes.setForeground(new java.awt.Color(0, 51, 102));
        jLabelConfiguracoes.setText("   Configurações");
        jLabelConfiguracoes.setOpaque(true);
        jLabelConfiguracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConfiguracoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelConfiguracoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelConfiguracoesMouseExited(evt);
            }
        });
        jPanelOpcoes.add(jLabelConfiguracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 50));

        jPanelMain.add(jPanelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 220, 230));

        jPanelCabecalho.setBackground(new java.awt.Color(0, 102, 153));
        jPanelCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PFC Manager");
        jPanelCabecalho.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 1370, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ricardo Mendes");
        jPanelCabecalho.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        jLabelOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_vert-24.png"))); // NOI18N
        jLabelOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpcoesMouseClicked(evt);
            }
        });
        jPanelCabecalho.add(jLabelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        jPanelMain.add(jPanelCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jPanelMenuLateral.setBackground(new java.awt.Color(0, 51, 102));
        jPanelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jPanelMenuLateral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 250, 100));

        jLabelRelatorios.setBackground(new java.awt.Color(0, 51, 102));
        jLabelRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRelatorios.setForeground(new java.awt.Color(0, 102, 153));
        jLabelRelatorios.setText("  Relatórios");
        jLabelRelatorios.setOpaque(true);
        jLabelRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRelatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRelatoriosMouseExited(evt);
            }
        });
        jPanelMenuLateral.add(jLabelRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 50));

        jLabelDashboard.setBackground(new java.awt.Color(0, 51, 102));
        jLabelDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDashboard.setForeground(new java.awt.Color(0, 102, 153));
        jLabelDashboard.setText("  Dashboard");
        jLabelDashboard.setOpaque(true);
        jLabelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDashboardMouseExited(evt);
            }
        });
        jPanelMenuLateral.add(jLabelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));

        jLabelProjetos.setBackground(new java.awt.Color(0, 51, 102));
        jLabelProjetos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelProjetos.setForeground(new java.awt.Color(0, 102, 153));
        jLabelProjetos.setText("  Projetos");
        jLabelProjetos.setOpaque(true);
        jLabelProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelProjetosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelProjetosMouseExited(evt);
            }
        });
        jPanelMenuLateral.add(jLabelProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 50));

        jLabelHistorico.setBackground(new java.awt.Color(0, 51, 102));
        jLabelHistorico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHistorico.setForeground(new java.awt.Color(0, 102, 153));
        jLabelHistorico.setText("  Histórico");
        jLabelHistorico.setOpaque(true);
        jLabelHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHistoricoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHistoricoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHistoricoMouseExited(evt);
            }
        });
        jPanelMenuLateral.add(jLabelHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 50));

        jLabelBancas.setBackground(new java.awt.Color(0, 51, 102));
        jLabelBancas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBancas.setForeground(new java.awt.Color(0, 102, 153));
        jLabelBancas.setText("  Bancas");
        jLabelBancas.setOpaque(true);
        jLabelBancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBancasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBancasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBancasMouseExited(evt);
            }
        });
        jPanelMenuLateral.add(jLabelBancas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 50));

        jLabelEquipes.setBackground(new java.awt.Color(0, 51, 102));
        jLabelEquipes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEquipes.setForeground(new java.awt.Color(0, 102, 153));
        jLabelEquipes.setText("  Equipes");
        jLabelEquipes.setOpaque(true);
        jLabelEquipes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEquipesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEquipesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEquipesMouseExited(evt);
            }
        });
        jPanelMenuLateral.add(jLabelEquipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        jPanelMain.add(jPanelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 620));

        jPanelConteudoCentral.setLayout(new java.awt.CardLayout());

        jPanelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Dashboard");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 10));

        jPanelDashboard.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanelDashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1120, 90));

        jPanelConteudoCentral.add(jPanelDashboard, "dashboard");

        jPanelProjetos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjetos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Projetos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 10));

        jPanelProjetos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 100));

        jLabelNovoProjeto.setBackground(new java.awt.Color(0, 51, 102));
        jLabelNovoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNovoProjeto.setForeground(new java.awt.Color(0, 102, 153));
        jLabelNovoProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovoProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-24.png"))); // NOI18N
        jLabelNovoProjeto.setText("Novo Projeto");
        jLabelNovoProjeto.setOpaque(true);
        jLabelNovoProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNovoProjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelNovoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(919, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelNovoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelProjetos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1120, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProjetos.setForeground(new java.awt.Color(0, 51, 102));
        jTableProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjetos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 940, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter24.png"))); // NOI18N
        jLabel4.setText("Selecione as opções de pesquisa:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 102));
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Tipo de Projeto Empresa:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 190, -1));

        jComboBoxTipoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxTipoProjeto.setForeground(new java.awt.Color(0, 51, 102));
        jComboBoxTipoProjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interno", "Externo" }));
        jPanel4.add(jComboBoxTipoProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Cliente:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Macrotema:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 190, -1));

        jComboBoxNegocio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxNegocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escola Técnica", "Serviços Técnicos", "Centro Universitário", "P&D&I", "Comércio", "Indústria", "Social", "CIMATEC", "CIMATEC PARK" }));
        jPanel4.add(jComboBoxNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 190, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Retorno Financeiro:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, -1));

        jComboBoxTipoProjetoEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxTipoProjetoEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesquisa", "Projeto", "Desenvolvimento de Produto", "Processo" }));
        jPanel4.add(jComboBoxTipoProjetoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 190, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("Tipo de Projeto:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 190, -1));

        jComboBoxMacrotema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sustentabilidade", "Inovação de produto", "Inovação de processo", "Otimização de Processo", "Atualização tecnológica", "Responsabilidade Social", "Construção de protótipos", "Desenvolvimento de ferramentas", "Plantas e modelagens", "Manuten-ção" }));
        jPanel4.add(jComboBoxMacrotema, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 30));

        jComboBoxRisco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alto", "Médio", "Baixo" }));
        jPanel4.add(jComboBoxRisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 190, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Tipo de Negócio:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Nível de Risco");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 190, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 51, 102));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("Até:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 30, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("De:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 30, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 51, 102));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("Status");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 190, -1));

        jComboBoxRisco1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Pendente" }));
        jPanel4.add(jComboBoxRisco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 190, 30));

        jPanelProjetos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1120, 430));

        jPanelConteudoCentral.add(jPanelProjetos, "projetos");

        jPanelEquipes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Equipes");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 51, 102));
        jPanel14.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 10));

        jPanelEquipes.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 100));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEquipes.setForeground(new java.awt.Color(0, 51, 102));
        jTableEquipes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableEquipes);

        jPanel15.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 940, 120));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 102));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter24.png"))); // NOI18N
        jLabel24.setText("Selecione as opções de pesquisa:");
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 102));
        jLabel25.setText("Gestor:");
        jPanel15.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 102));
        jLabel28.setText("Aluno:");
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 190, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 102));
        jLabel29.setText("Turma:");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 190, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 51, 102));
        jPanel15.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 190, 30));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 51, 102));
        jPanel15.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 30));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 51, 102));
        jPanel15.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 30));

        jPanelEquipes.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1120, 430));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNovaBanca1.setBackground(new java.awt.Color(0, 51, 102));
        jLabelNovaBanca1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNovaBanca1.setForeground(new java.awt.Color(0, 102, 153));
        jLabelNovaBanca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovaBanca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-24.png"))); // NOI18N
        jLabelNovaBanca1.setText("Nova Equipe");
        jLabelNovaBanca1.setOpaque(true);
        jLabelNovaBanca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNovaBanca1MouseClicked(evt);
            }
        });
        jPanel16.add(jLabelNovaBanca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, 180, 50));

        jPanelEquipes.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1120, 90));

        jPanelConteudoCentral.add(jPanelEquipes, "equipes");

        jPanelBancas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBancas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Bancas");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 51, 102));
        jPanel11.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 10));

        jPanelBancas.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 100));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNovaBanca.setBackground(new java.awt.Color(0, 51, 102));
        jLabelNovaBanca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNovaBanca.setForeground(new java.awt.Color(0, 102, 153));
        jLabelNovaBanca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovaBanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-24.png"))); // NOI18N
        jLabelNovaBanca.setText("Nova Banca");
        jLabelNovaBanca.setOpaque(true);
        jLabelNovaBanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNovaBancaMouseClicked(evt);
            }
        });
        jPanel12.add(jLabelNovaBanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, 180, 50));

        jLabelPesquisarBanca.setBackground(new java.awt.Color(0, 51, 102));
        jLabelPesquisarBanca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPesquisarBanca.setForeground(new java.awt.Color(0, 102, 153));
        jLabelPesquisarBanca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPesquisarBanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-24.png"))); // NOI18N
        jLabelPesquisarBanca.setText("Pesquisar Banca");
        jLabelPesquisarBanca.setOpaque(true);
        jLabelPesquisarBanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPesquisarBancaMouseClicked(evt);
            }
        });
        jPanel12.add(jLabelPesquisarBanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 180, 50));

        jPanelBancas.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1120, 90));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBancas.setForeground(new java.awt.Color(0, 51, 102));
        jTableBancas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableBancas);

        jPanel13.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 940, 120));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter24.png"))); // NOI18N
        jLabel8.setText("Selecione as opções de pesquisa:");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("Orientador:");
        jPanel13.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 102));
        jLabel26.setText("GTA:");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 190, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 102));
        jLabel27.setText("Docente:");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 190, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 51, 102));
        jPanel13.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 190, 30));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 51, 102));
        jPanel13.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 30));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 51, 102));
        jPanel13.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 30));

        jPanelBancas.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1120, 430));

        jPanelConteudoCentral.add(jPanelBancas, "bancas");

        jPanelHistorico.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHistorico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 10));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Histórico");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        jPanelHistorico.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanelHistorico.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1120, 90));

        jPanelConteudoCentral.add(jPanelHistorico, "historico");

        jPanelRelatorios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRelatorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Relatórios");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 51, 102));
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 10));

        jPanelRelatorios.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 100));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelRelatorios.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1120, 90));

        jPanelConteudoCentral.add(jPanelRelatorios, "relatorios");

        jPanelMain.add(jPanelConteudoCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1120, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashboardMouseEntered
        // TODO add your handling code here:
        jLabelDashboard.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_jLabelDashboardMouseEntered

    private void jLabelDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashboardMouseExited
        // TODO add your handling code here:
        jLabelDashboard.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_jLabelDashboardMouseExited

    private void jLabelProjetosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosMouseEntered
        // TODO add your handling code here:
        jLabelProjetos.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_jLabelProjetosMouseEntered

    private void jLabelProjetosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosMouseExited
        // TODO add your handling code here:
        jLabelProjetos.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_jLabelProjetosMouseExited

    private void jLabelHistoricoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistoricoMouseEntered
        // TODO add your handling code here:
        jLabelHistorico.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_jLabelHistoricoMouseEntered

    private void jLabelHistoricoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistoricoMouseExited
        // TODO add your handling code here:
        jLabelHistorico.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_jLabelHistoricoMouseExited

    private void jLabelRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRelatoriosMouseEntered
        // TODO add your handling code here:
        jLabelRelatorios.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_jLabelRelatoriosMouseEntered

    private void jLabelRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRelatoriosMouseExited
        // TODO add your handling code here:
        jLabelRelatorios.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_jLabelRelatoriosMouseExited

    private void jLabelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashboardMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelConteudoCentral.getLayout();
        cl.show(jPanelConteudoCentral, "dashboard");
    }//GEN-LAST:event_jLabelDashboardMouseClicked

    private void jLabelProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelConteudoCentral.getLayout();
        cl.show(jPanelConteudoCentral, "projetos");
    }//GEN-LAST:event_jLabelProjetosMouseClicked

    private void jLabelHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistoricoMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelConteudoCentral.getLayout();
        cl.show(jPanelConteudoCentral, "historico");
    }//GEN-LAST:event_jLabelHistoricoMouseClicked

    private void jLabelRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRelatoriosMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelConteudoCentral.getLayout();
        cl.show(jPanelConteudoCentral, "relatorios");
    }//GEN-LAST:event_jLabelRelatoriosMouseClicked

    private void jLabelNovoProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNovoProjetoMouseClicked
        // TODO add your handling code here:
        TelaCadastroProjeto tela = new TelaCadastroProjeto();
        tela.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabelNovoProjetoMouseClicked

    private void jLabelMinhaContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinhaContaMouseEntered
        // TODO add your handling code here:
        jLabelMinhaConta.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jLabelMinhaContaMouseEntered

    private void jLabelOpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcoesMouseClicked
        // TODO add your handling code here:
        if (!jPanelOpcoes.isVisible()) {
            jPanelOpcoes.setVisible(true);
        } else {
            jPanelOpcoes.setVisible(false);
        }
    }//GEN-LAST:event_jLabelOpcoesMouseClicked

    private void jLabelMinhaContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinhaContaMouseExited
        // TODO add your handling code here:
        jLabelMinhaConta.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabelMinhaContaMouseExited

    private void jLabelUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuariosMouseEntered
        // TODO add your handling code here:
        jLabelUsuarios.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jLabelUsuariosMouseEntered

    private void jLabelUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuariosMouseExited
        // TODO add your handling code here:
        jLabelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabelUsuariosMouseExited

    private void jLabelConfiguracoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfiguracoesMouseEntered
        // TODO add your handling code here:
        jLabelConfiguracoes.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jLabelConfiguracoesMouseEntered

    private void jLabelConfiguracoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfiguracoesMouseExited
        // TODO add your handling code here:
        jLabelConfiguracoes.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabelConfiguracoesMouseExited

    private void jLabelSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSairMouseEntered
        // TODO add your handling code here:
        jLabelSair.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_jLabelSairMouseEntered

    private void jLabelSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSairMouseExited
        // TODO add your handling code here:
        jLabelSair.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabelSairMouseExited

    private void jLabelMinhaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinhaContaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinhaContaMouseClicked

    private void jLabelUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuariosMouseClicked
        // TODO add your handling code here:
        TelaCadastroUsuario tela = new TelaCadastroUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jLabelUsuariosMouseClicked

    private void jLabelConfiguracoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfiguracoesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelConfiguracoesMouseClicked

    private void jLabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelSairMouseClicked

    private void jLabelBancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBancasMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelConteudoCentral.getLayout();
        cl.show(jPanelConteudoCentral, "bancas");
        
        criarTabelaBanca();
    }//GEN-LAST:event_jLabelBancasMouseClicked

    private void jLabelBancasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBancasMouseEntered
        // TODO add your handling code here:
        jLabelBancas.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_jLabelBancasMouseEntered

    private void jLabelBancasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBancasMouseExited
        // TODO add your handling code here:
        jLabelBancas.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBancasMouseExited

    private void jLabelNovaBancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNovaBancaMouseClicked
        // TODO add your handling code here:
        TelaCadastroBanca tela = new TelaCadastroBanca();
        tela.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabelNovaBancaMouseClicked

    private void jLabelEquipesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEquipesMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelConteudoCentral.getLayout();
        cl.show(jPanelConteudoCentral, "equipes");
    }//GEN-LAST:event_jLabelEquipesMouseClicked

    private void jLabelEquipesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEquipesMouseEntered
        // TODO add your handling code here:
        jLabelEquipes.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_jLabelEquipesMouseEntered

    private void jLabelEquipesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEquipesMouseExited
        // TODO add your handling code here:
        jLabelEquipes.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_jLabelEquipesMouseExited

    private void jLabelNovaBanca1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNovaBanca1MouseClicked
        // TODO add your handling code here:
        TelaCadastroEquipe tela = new TelaCadastroEquipe();
        tela.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabelNovaBanca1MouseClicked

    private void jLabelPesquisarBancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPesquisarBancaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabelPesquisarBancaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxMacrotema;
    private javax.swing.JComboBox<String> jComboBoxNegocio;
    private javax.swing.JComboBox<String> jComboBoxRisco;
    private javax.swing.JComboBox<String> jComboBoxRisco1;
    private javax.swing.JComboBox<String> jComboBoxTipoProjeto;
    private javax.swing.JComboBox<String> jComboBoxTipoProjetoEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBancas;
    private javax.swing.JLabel jLabelConfiguracoes;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelEquipes;
    private javax.swing.JLabel jLabelHistorico;
    private javax.swing.JLabel jLabelMinhaConta;
    private javax.swing.JLabel jLabelNovaBanca;
    private javax.swing.JLabel jLabelNovaBanca1;
    private javax.swing.JLabel jLabelNovoProjeto;
    private javax.swing.JLabel jLabelOpcoes;
    private javax.swing.JLabel jLabelPesquisarBanca;
    private javax.swing.JLabel jLabelProjetos;
    private javax.swing.JLabel jLabelRelatorios;
    private javax.swing.JLabel jLabelSair;
    private javax.swing.JLabel jLabelUsuarios;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBancas;
    private javax.swing.JPanel jPanelCabecalho;
    private javax.swing.JPanel jPanelConteudoCentral;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelEquipes;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMenuLateral;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JPanel jPanelProjetos;
    private javax.swing.JPanel jPanelRelatorios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTableBancas;
    private javax.swing.JTable jTableEquipes;
    private javax.swing.JTable jTableProjetos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void criarTabelaBanca() {
        DefaultTableModel modeloTabelaBanca = new DefaultTableModel(new String []{"Orientador","GTA","Docente"},0);
        
        jTableBancas.setModel(modeloTabelaBanca);
        
        BancaDAL bDAL = new BancaDAL();
            
        ArrayList<Banca> bancas = bDAL.consultarTodos();
        
        for(int i = 0 ; i < bancas.size(); i++){
        modeloTabelaBanca.addRow(new String[]{
            bancas.get(i).getId()+"",
            bancas.get(i).getOrientador(),
            bancas.get(i).getGta(),
            bancas.get(i).getDocente(),
            
        });
    }
        
    }

}
