package view;

import dal.BancaDAL;
import dal.DocenteDAL;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.Banca;
import model.Docente;

public class TelaCadastroBanca extends javax.swing.JFrame {

    public TelaCadastroBanca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRepCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxOrientador = new javax.swing.JComboBox<>();
        jComboBoxPedagogia = new javax.swing.JComboBox<>();
        jComboBoxGta = new javax.swing.JComboBox<>();
        jComboBoxDocente = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(680, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Nova Banca");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 32));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Orientador Técnico:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("GPE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Docente:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel3.setMinimumSize(new java.awt.Dimension(657, 57));
        jPanel3.setPreferredSize(new java.awt.Dimension(657, 57));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 120, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setLabel("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 120, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 480, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_close_1814098.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Representante do Cliente:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 210, -1));

        jTextFieldRepCliente.setMinimumSize(new java.awt.Dimension(13, 37));
        jTextFieldRepCliente.setPreferredSize(new java.awt.Dimension(13, 37));
        jTextFieldRepCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRepClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldRepCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 380, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Pedagogia:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, -1));

        jComboBoxOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrientadorActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxOrientador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));

        jPanel2.add(jComboBoxPedagogia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, -1));

        jPanel2.add(jComboBoxGta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        jPanel2.add(jComboBoxDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
//        // TODO add your handling code here:

        BancaDAL dal = new BancaDAL();
        Banca banca = new Banca();

        Docente docente = new Docente();
        Docente gta = new Docente();
        Docente orientador = new Docente();
        Docente pedagogia = new Docente();

        docente = (Docente) jComboBoxDocente.getSelectedItem();
        gta = (Docente) jComboBoxGta.getSelectedItem();
        orientador = (Docente) jComboBoxOrientador.getSelectedItem();
        pedagogia = (Docente) jComboBoxPedagogia.getSelectedItem();

        banca.setRepresentanteClinete(jTextFieldRepCliente.getText());
        banca.setDocente(docente);
        banca.setGta(gta);
        banca.setOrientador(orientador);
        banca.setPedagogia(pedagogia);

        dal.save(banca);

//        try{
//            Banca banca = new Banca();
//            
//            banca.setOrientador(jTextFieldOrientador.getText());
//            banca.setGta(jTextFieldGTA.getText());
//            banca.setDocente(jTextFieldDocente.getText());
//            
//            BancaDAL bDAL = new BancaDAL();
//            
//            bDAL.inserir(banca);
//            
//            JOptionPane.showMessageDialog(this, "Banca cadastrada com sucesso!");
//
//            this.dispose();
//        } catch (SQLException ex) {
//            Logger.getLogger(TelaCadastroBanca.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "Erro 1: Não foi possível acessar o banco de dados.");
//        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jTextFieldRepClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRepClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldRepClienteActionPerformed

    private void jComboBoxOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrientadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxOrientadorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DocenteDAL dal = new DocenteDAL();
        List<Docente> docentes = dal.findAll();

        for (Docente d : docentes) {
            jComboBoxDocente.addItem(d);
        }
        for (Docente d : docentes) {
            jComboBoxGta.addItem(d);
        }
        for (Docente d : docentes) {
            jComboBoxOrientador.addItem(d);
        }
        for (Docente d : docentes) {
            jComboBoxPedagogia.addItem(d);
        }

//        DefaultComboBoxModel modelOrientador = (DefaultComboBoxModel) jComboBoxOrientador.getModel();
//        modelOrientador.removeAllElements();
//        for (Docente orientadores : docentes) {
//            modelOrientador.addElement(orientadores.getNome());
//        }
//
//        DefaultComboBoxModel modelGta = (DefaultComboBoxModel) jComboBoxGpe.getModel();
//        modelGta.removeAllElements();
//        for (Docente gtas : docentes) {
//            modelGta.addElement(gtas.getNome());
//        }
//
//        DefaultComboBoxModel modelDocente = (DefaultComboBoxModel) jComboBoxDocente.getModel();
//        modelDocente.removeAllElements();
//        for (Docente docente : docentes) {
//            modelDocente.addElement(docente.getNome());
//        }
//
//        DefaultComboBoxModel modelPedagogia = (DefaultComboBoxModel) jComboBoxPedagogia.getModel();
//        modelPedagogia.removeAllElements();
//        for (Docente pedagogias : docentes) {
//            modelPedagogia.addElement(pedagogias.getNome());
//        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroBanca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Object> jComboBoxDocente;
    private javax.swing.JComboBox<Object> jComboBoxGta;
    private javax.swing.JComboBox<Object> jComboBoxOrientador;
    private javax.swing.JComboBox<Object> jComboBoxPedagogia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldRepCliente;
    // End of variables declaration//GEN-END:variables
}
