/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dal.EquipeDAL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Banca;
import model.Equipe;

/**
 *
 * @author Caio
 */
public class TelaCadastroEquipe extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEquipe
     */
    public TelaCadastroEquipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldGestor = new javax.swing.JTextField();
        jTextFieldAluno1 = new javax.swing.JTextField();
        jTextFieldAluno2 = new javax.swing.JTextField();
        jTextFieldAluno3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTurma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(520, 580));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(680, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Nova Equipe");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 32));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Gestor do projeto:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Aluno 1:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Aluno 2:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPanel3.setMinimumSize(new java.awt.Dimension(657, 57));
        jPanel3.setPreferredSize(new java.awt.Dimension(657, 57));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCadastrar(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 120, -1));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 51, 102));
        jButtonCancelar.setLabel("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelar(evt);
            }
        });
        jPanel3.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 120, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 480, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_close_1814098.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5jLabelCloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Aluno 3:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextFieldGestor.setMinimumSize(new java.awt.Dimension(13, 37));
        jTextFieldGestor.setPreferredSize(new java.awt.Dimension(13, 37));
        jTextFieldGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGestorActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 380, -1));

        jTextFieldAluno1.setMinimumSize(new java.awt.Dimension(13, 37));
        jTextFieldAluno1.setPreferredSize(new java.awt.Dimension(13, 37));
        jTextFieldAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAluno1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldAluno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 380, -1));

        jTextFieldAluno2.setMinimumSize(new java.awt.Dimension(13, 37));
        jTextFieldAluno2.setPreferredSize(new java.awt.Dimension(13, 37));
        jTextFieldAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAluno2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldAluno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 380, -1));

        jTextFieldAluno3.setMinimumSize(new java.awt.Dimension(13, 37));
        jTextFieldAluno3.setPreferredSize(new java.awt.Dimension(13, 37));
        jTextFieldAluno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAluno3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldAluno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 380, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Turma:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jTextFieldTurma.setMinimumSize(new java.awt.Dimension(13, 37));
        jTextFieldTurma.setPreferredSize(new java.awt.Dimension(13, 37));
        jTextFieldTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTurmaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5jLabelCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5jLabelCloseMouseClicked

    private void jTextFieldGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGestorActionPerformed

    private void jTextFieldAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAluno1ActionPerformed

    private void jTextFieldAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAluno2ActionPerformed

    private void jTextFieldAluno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAluno3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAluno3ActionPerformed

    private void jTextFieldTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTurmaActionPerformed

    private void JButtonCadastrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCadastrar
//        // TODO add your handling code here:
//        try{
//            Equipe equip = new Equipe();
//            
//            equip.setGestor(jTextFieldGestor.getText());
//            equip.setAluno1(jTextFieldAluno1.getText());
//            equip.setAluno2(jTextFieldAluno2.getText());
//            equip.setAluno3(jTextFieldAluno3.getText());
//            
//            EquipeDAL eDAL = new EquipeDAL();
//            eDAL.inserir(equip);
//            
//            JOptionPane.showMessageDialog(this, "Equipe cadastrada com sucesso!");
//            
//            this.dispose();
//        }catch (SQLException ex){
//            Logger.getLogger(TelaCadastroBanca.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "Erro 1: Não foi possível acessar o banco de dados.");
//        }
        
        
    }//GEN-LAST:event_JButtonCadastrar

    private void JButtonCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelar
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JButtonCancelar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEquipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAluno1;
    private javax.swing.JTextField jTextFieldAluno2;
    private javax.swing.JTextField jTextFieldAluno3;
    private javax.swing.JTextField jTextFieldGestor;
    private javax.swing.JTextField jTextFieldTurma;
    // End of variables declaration//GEN-END:variables
}
