/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dal.ClienteDAL;
import java.awt.CardLayout;
import model.Cliente;

/**
 *
 * @author rpmen
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelCadastroCliente1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jTextFieldNomeFantasia = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelProximo1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jPanelCadastroCliente2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeRepresentante = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEmailRepresentante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTelefoneRepresentante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabelProximo2 = new javax.swing.JLabel();
        jLabelVoltar1 = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jPanelCadastroCliente3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProblema = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSolucao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();
        jLabelSalvar = new javax.swing.JLabel();
        jLabelVoltar2 = new javax.swing.JLabel();
        jLabelClose2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanelCadastroCliente1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastroCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Cadastro de Cliente");
        jPanelCadastroCliente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Razão Social:");
        jPanelCadastroCliente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Nome Fantasia:");
        jPanelCadastroCliente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Endereço:");
        jPanelCadastroCliente1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jTextFieldRazaoSocial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRazaoSocial.setForeground(new java.awt.Color(0, 51, 102));
        jPanelCadastroCliente1.add(jTextFieldRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 550, -1));

        jTextFieldNomeFantasia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldNomeFantasia.setForeground(new java.awt.Color(0, 51, 102));
        jPanelCadastroCliente1.add(jTextFieldNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 550, -1));

        jTextFieldEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldEndereco.setForeground(new java.awt.Color(0, 51, 102));
        jPanelCadastroCliente1.add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 550, -1));

        jLabelProximo1.setBackground(new java.awt.Color(0, 102, 153));
        jLabelProximo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelProximo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProximo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProximo1.setText("Próximo");
        jLabelProximo1.setOpaque(true);
        jLabelProximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProximo1MouseClicked(evt);
            }
        });
        jPanelCadastroCliente1.add(jLabelProximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 190, 60));

        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_close_1814098.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanelCadastroCliente1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel2.add(jPanelCadastroCliente1, "cadastroCliente1");

        jPanelCadastroCliente2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastroCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Cadastro de Cliente");
        jPanelCadastroCliente2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTextFieldNomeRepresentante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldNomeRepresentante.setForeground(new java.awt.Color(0, 51, 102));
        jPanelCadastroCliente2.add(jTextFieldNomeRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 550, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("E-mail do Representante:");
        jPanelCadastroCliente2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jTextFieldEmailRepresentante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldEmailRepresentante.setForeground(new java.awt.Color(0, 51, 102));
        jPanelCadastroCliente2.add(jTextFieldEmailRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 550, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Telefone do Representante:");
        jPanelCadastroCliente2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jTextFieldTelefoneRepresentante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldTelefoneRepresentante.setForeground(new java.awt.Color(0, 51, 102));
        jPanelCadastroCliente2.add(jTextFieldTelefoneRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 550, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Nome do Representante:");
        jPanelCadastroCliente2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabelProximo2.setBackground(new java.awt.Color(0, 102, 153));
        jLabelProximo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelProximo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProximo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProximo2.setText("Próximo");
        jLabelProximo2.setOpaque(true);
        jLabelProximo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProximo2MouseClicked(evt);
            }
        });
        jPanelCadastroCliente2.add(jLabelProximo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 190, 60));

        jLabelVoltar1.setBackground(new java.awt.Color(0, 102, 153));
        jLabelVoltar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVoltar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVoltar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVoltar1.setText("Voltar");
        jLabelVoltar1.setOpaque(true);
        jLabelVoltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVoltar1MouseClicked(evt);
            }
        });
        jPanelCadastroCliente2.add(jLabelVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 190, 60));

        jLabelClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_close_1814098.png"))); // NOI18N
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        jPanelCadastroCliente2.add(jLabelClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel2.add(jPanelCadastroCliente2, "cadastroCliente2");

        jPanelCadastroCliente3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastroCliente3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Cadastro de Cliente");
        jPanelCadastroCliente3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Qual a solução ele deseja:");
        jPanelCadastroCliente3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Quais os resultados ele espera:");
        jPanelCadastroCliente3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("Qual o problema o cliente tem:");
        jPanelCadastroCliente3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jTextAreaProblema.setColumns(20);
        jTextAreaProblema.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProblema);

        jPanelCadastroCliente3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 550, 70));

        jTextAreaSolucao.setColumns(20);
        jTextAreaSolucao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSolucao);

        jPanelCadastroCliente3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 550, 70));

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setRows(5);
        jScrollPane3.setViewportView(jTextAreaResultado);

        jPanelCadastroCliente3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 550, 70));

        jLabelSalvar.setBackground(new java.awt.Color(0, 102, 153));
        jLabelSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalvar.setText("Salvar");
        jLabelSalvar.setOpaque(true);
        jLabelSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalvarMouseClicked(evt);
            }
        });
        jPanelCadastroCliente3.add(jLabelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 190, 60));

        jLabelVoltar2.setBackground(new java.awt.Color(0, 102, 153));
        jLabelVoltar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVoltar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVoltar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVoltar2.setText("Voltar");
        jLabelVoltar2.setOpaque(true);
        jLabelVoltar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVoltar2MouseClicked(evt);
            }
        });
        jPanelCadastroCliente3.add(jLabelVoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 190, 60));

        jLabelClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_close_1814098.png"))); // NOI18N
        jLabelClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose2MouseClicked(evt);
            }
        });
        jPanelCadastroCliente3.add(jLabelClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel2.add(jPanelCadastroCliente3, "cadastroCliente3");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProximo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProximo1MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "cadastroCliente2");
    }//GEN-LAST:event_jLabelProximo1MouseClicked

    private void jLabelProximo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProximo2MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "cadastroCliente3");
    }//GEN-LAST:event_jLabelProximo2MouseClicked

    private void jLabelVoltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVoltar1MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "cadastroCliente1");
    }//GEN-LAST:event_jLabelVoltar1MouseClicked

    private void jLabelVoltar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVoltar2MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "cadastroCliente2");
    }//GEN-LAST:event_jLabelVoltar2MouseClicked

    private void jLabelSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalvarMouseClicked
        // TODO add your handling code here:
        ClienteDAL dal = new ClienteDAL();
        Cliente cliente = new Cliente();
        
        cliente.setRazaoSocial(jTextFieldRazaoSocial.getText());
        cliente.setNomeFantasia(jTextFieldNomeFantasia.getText());
        cliente.setEndereço(jTextFieldEndereco.getText());
        cliente.setNomeRepresentante(jTextFieldNomeRepresentante.getText());
        cliente.setTelefoneRepresentante(jTextFieldTelefoneRepresentante.getText());
        cliente.setEmailRepresentante(jTextFieldEmailRepresentante.getText());
        cliente.setProblema(jTextAreaProblema.getText());
        cliente.setSolucaoDesejada(jTextAreaSolucao.getText());
        cliente.setResultadoEsperado(jTextAreaResultado.getText());
        
        dal.save(cliente);
    }//GEN-LAST:event_jLabelSalvarMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jLabelClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelClose2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelClose2;
    private javax.swing.JLabel jLabelProximo1;
    private javax.swing.JLabel jLabelProximo2;
    private javax.swing.JLabel jLabelSalvar;
    private javax.swing.JLabel jLabelVoltar1;
    private javax.swing.JLabel jLabelVoltar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadastroCliente1;
    private javax.swing.JPanel jPanelCadastroCliente2;
    private javax.swing.JPanel jPanelCadastroCliente3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaProblema;
    private javax.swing.JTextArea jTextAreaResultado;
    private javax.swing.JTextArea jTextAreaSolucao;
    private javax.swing.JTextField jTextFieldEmailRepresentante;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNomeFantasia;
    private javax.swing.JTextField jTextFieldNomeRepresentante;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JTextField jTextFieldTelefoneRepresentante;
    // End of variables declaration//GEN-END:variables
}
